from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
generate_mono_repository_global_tag = true
tag_prefix="v"
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false

pre_bump_hooks = [
    "mvn versions:set -DnewVersion={{version}}"
]

post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
    "mvn versions:set -DnewVersion={{version+minor-SNAPSHOT}}",
    "git add pom.xml",
    "cog commit chore \"bump snapshot to {{version+1minor-SNAPSHOT}}\" --skip-ci",
    "git push",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
improvement = { changelog_title = "Improvements", bump_patch = true }
chore = { changelog_title = "Chore", omit_from_changelog = true }
ci = { changelog_title = "", omit_from_changelog = true }
perf = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "command-feign-client"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" }
]

[bump_profiles]

[packages]
